language: java
dist: xenial
os:
  - linux
  - osx

jobs:
  include:
    - stage: building
      before_script: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      script: mvn compile
    - stage: testing
      before_script: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      script: mvn test
      after_success: bash <(curl -s https://codecov.io/bash)